### ISSUE TITLE
ci(security): leverage soos.io's free offerings 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2561]
### Description

They have a free dependency scanner, similar to GitHub's robots, but it seems to find more CVEs at a quick glance.

https://app.soos.io/dashboard/

### Acceptance Criteria
1. Evaluate if there is an actual upside
2. Make sure that the CI resource usage doesn't go up significantly
3. Strictly free-tier features only

**Comment by jagpreetsinghsasan** [comment]
soos.io offerings for finding security vulnerabilities are good but the free tier (refered as Community edition) `does not offer` any of the vital integrations, like via `github-actions`, `script` which uses their npm package to find vulnerabilites etc etc. (attached screenshot of the list of integrations provided `outside` free tier)
![image](https://github.com/hyperledger/cacti/assets/56861721/614f044d-c714-4be0-acfd-ea8e843f54ac)

I tried the tool in trial mode and it seems to be comparable to Trivy scans, but since we are just evaluating the free tier, I would personally not recommend this tool, because managing vulnerabilities from the soos.io dashboard is the only option available which is not a managable thing from a team's perspective (like handing out vulnerability tasks to other team members and lots of to-and-from communication just because they cant access the board). Also the lack of APIs in free mode can lead to a substantial manual work, which is currently automated by Trivy based github actions.

Requesting @petermetz review on this to decide further investigation/closure on the task.

**Comment by petermetz** [comment]
@jagpreetsinghsasan All of that makes sense and I agree. My take: Based on your investigation we can close this issue given that we have documented the findings and the decision seems pretty clear cut based on the information presented. If any of this changes we can re-open and re-evaluate as needed. Thank you for the research and the work!
