### ISSUE TITLE
refactor(cacti-cmd-gui-app): rename to cacti-ledger-browser

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2572]
Rename the package to something more specific so that it doesn't squat on the entire
namespace of all GUI applications we ever wrote/will write.

This would be a breaking change but luckily we haven't released a new version of
it to npm yet so renaming it now is easy.

**Comment by outSH** [comment]
Well, the GUI was meant to be common and extensible, I have a branch somewhere where each app is even separated from each other but I don't have time to push this forward. I see the point of making room for more GUI apps, but I don't like the name `cacti-gui-tx-viewer` since it already shows blocks, tokens and is meant to to much more in the future. Maybe `cacti-gui-viewer` / `cacti-gui-browser` ? Or something linked to persistence plugins, but I don't have any specific idea.

@izuru0 @takeutak

**Comment by izuru0** [comment]
I see the points made by both of @petermetz and @outSH 
let me think about the name that is 'just right' for our app
wait for a day or two :)

**Comment by izuru0** [comment]
how about `cacti-ledger-viewer` or `cacti-ledger-browser` ?
these are specific enough about what this app lets you see

**Comment by petermetz** [comment]
@outSH @izuru0 Sorry for the slow response! Fair points all around! 

> how about `cacti-ledger-viewer` or `cacti-ledger-browser` ?

Works for me! I see that @outSH thumbs-upped it as well, so I'll update the PR accordingly and re-request review! Thank you both!
