### ISSUE TITLE
perf(cmd-api-server): add continuous benchmarking with JMeter 

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2672]
### Description

https://github.com/benchmark-action/github-action-benchmark

### Acceptance Criteria
1. Performance regressions are reported for each pull-request
2. Besu and Corda plugins' endpoints are covered by the benchmark.
3. Use JMeter for the performance tests (open to other implementations but the NodeJS package ecosystem seems very immature compared to JMeter in this regard)

**Comment by ruzell22** [comment]
Hello @petermetz , upon trying the benchmarkjs, it is working well and fine when testing the fibonacci sequence as benchmark performance testing. However, when trying to make it to test the connector besu contract, which is in typescript file format, it is requiring that the ts files would be transpiled to js file format before it can be used for performance testing. Transpiling was not the ideal solution because it would need to transpile whenever it needs to test with different contract or package. 

With that, we tried looking for another library under jmeter that is for typescript but to no avail. What can you suggest, should we find a different library that can use the contract in typescript file format or should we park the ticket for now? Thank you.

**Comment by petermetz** [comment]
> Hello @petermetz , upon trying the benchmarkjs, it is working well and fine when testing the fibonacci sequence as benchmark performance testing. However, when trying to make it to test the connector besu contract, which is in typescript file format, it is requiring that the ts files would be transpiled to js file format before it can be used for performance testing. Transpiling was not the ideal solution because it would need to transpile whenever it needs to test with different contract or package.
> 
> With that, we tried looking for another library under jmeter that is for typescript but to no avail. What can you suggest, should we find a different library that can use the contract in typescript file format or should we park the ticket for now? Thank you.

@ruzell22 No worries, I'll help out!

**Comment by petermetz** [comment]
@ruzell22 Please work backwards from this: https://github.com/hyperledger/cacti/pull/3007

I highly recommend using your fork for testing changes:
1. Disable all the github workflows on the web gui except for ci.yaml
2. Add besu and corda benchmark tests using the linked PR as inspiration.
