### ISSUE TITLE
fix(plugin-persistence-fabric): remedy SQL injection in db-client

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#2757]
SQL Injection 

Risk Rating: High 

Category: Injection 

## Description 

The application's initializePlugin method executes an SQL query with query, application constructs this SQL query by embedding an untrusted string into the query without proper sanitization. The concatenated string is submitted to the database, where it is parsed and executed accordingly. 

An attacker would be able to inject arbitrary syntax and data into the SQL query, by crafting a malicious payload and providing it via the input readFileSync; this input is then read by the initializePlugin method and then flows through the code, into a query and to the database server - without sanitization. This may enable an SQL Injection attack. 

## Impact 

An attacker could directly access all of the system's data. The attacker would likely be able to steal any sensitive information stored by the system, including private user information, credit card details, proprietary business data, and any other secret data. Likewise, the attacker could possibly modify or erase existing data, or even add new bogus data. In some scenarios, it may even be possible to execute code on the database.  

In addition to disclosing or altering confidential information directly, this vulnerability might also be used to achieve secondary effects, such as bypassing authentication, subverting security checks, or forging a data trail.   

Further increasing the likelihood of exploit is the fact that this flaw is easy for attackers to find, and easy to exploit. 

## Remediation Recommendation 

Validate all untrusted data, regardless of source. Validation should be based on a whitelist: accept only data fitting a specified structure, rather than reject bad patterns.  

In particular, check for: 

- Data type 
- Size 
- Range 
- Format 
- Expected values. 

---

- Restrict access to database objects and functionality, according to the Principle of Least Privilege. 
- Do not use dynamically concatenate strings to construct SQL queries.  
- Prefer using DB Stored Procedures for all data access, instead of ad-hoc dynamic queries.  
- Instead of unsafe string concatenation, use secure database components such as parameterized queries and object bindings (for example, commands and parameters).  
- Alternatively, an even better solution is to use an ORM library, in order to pre-define and encapsulate the allowed commands enabled for the application, instead of dynamically accessing the database directly. In this way the code plane and data plane should be isolated from each other. 
Data validation can be performed effectively using a secure library, such as OWASP's Encoder or ESAPI libraries.  

## Affected Files:

`packages\cactus-plugin-persistence-fabric\src\main\typescript\db-client\db-client.ts `

<img width="683" alt="image" src="https://github.com/hyperledger/cacti/assets/1583231/ca7a5b04-bb23-444e-a753-95b270e9203c">

Source: `APP PE Hyperledger Cacti v2.0.0 - Static Application Assessment Report.odt`

cc: @takeutak @izuru0 @outSH

**Comment by VRamakrishna** [comment]
I think `Prefer using DB Stored Procedures for all data access, instead of ad-hoc dynamic queries.` sounds like the most reasonable remediation. Other methods seem to involve fairly complex parsing or only handle a narrow attack vector. I don't know if the API itself differentiates stored procedure calls from arbitrary SQL queries. If it does, that's an easy code change. Otherwise, some simple parsing logic logic should be able to differentiate ad hoc queries from procedure calls.

**Comment by petermetz** [comment]
> I think `Prefer using DB Stored Procedures for all data access, instead of ad-hoc dynamic queries.` sounds like the most reasonable remediation. Other methods seem to involve fairly complex parsing or only handle a narrow attack vector. I don't know if the API itself differentiates stored procedure calls from arbitrary SQL queries. If it does, that's an easy code change. Otherwise, some simple parsing logic logic should be able to differentiate ad hoc queries from procedure calls.

^^ +1 stored procedures / parameterized queries are the easiest way to narrow the attack surface down.

**Comment by outSH** [comment]
@petermetz @VRamakrishna 

> +1 stored procedures / parameterized queries are the easiest way to narrow the attack surface down.

Both persistent plugins use stored procedures and parametrized queries for all operations (see this file in full and simialar in ethereum persistence plugin). The warning here is concerned about schema initialization which:
- Runs only when schema was not initialized
- Reads file directly from this package (like `import` statement).

So I'd treat it as false positive since the only attack vector is to modify package on a server and if someone can do that they could modify this JS file as easily and do anything.

**Comment by petermetz** [comment]
@outSH Works for me! Closing as won't fix.
