### ISSUE TITLE
test(ci): require some core tests

### ISSUE THREAD

**Issue by outSH** [hyperledger/cacti#2966]
I'd like to require certain tests to always pass before PR can be merged. The list is small to require only tests with no false-nagative results and no complex setup (i.e. no functional test suites). My proposition (in addition to already enabled weaver tests) would be:

- Commit Lint / commitlint (pull_request) 
- Lint PR / Validate PR title (pull_request_target) 
- Cactus_CI / DCI-Lint (pull_request) 
- Cactus_CI / build-dev (pull_request) 
- Cactus_CI / yarn_lint (pull_request) 
- Cactus_CI / yarn_codegen (pull_request) 
- Cactus_CI / yarn_custom_checks (pull_request) 
  - after https://github.com/hyperledger/cacti/pull/2959 is merged
- Cactus_CI / yarn_tools_validate_bundle_names (pull_request) 
- Cactus_CI / cactus-common (pull_request) 
- Cactus_CI / cactus-core (pull_request) 
- Cactus_CI / cactus-core-api (pull_request) 

@petermetz @takeutak @izuru0 @jagpreetsinghsasan @vramakrishna @sandeepnRES please let me know what you think.

**Comment by petermetz** [comment]
@outSH Thank you for keeping track of these! Most of them are now enabled and set as required so we are making great progress, BUT there is one that I'm still looking into: the cactus-core pkg's tests for some reason pass fine on my local environment but fail in the CI and without any kind of error logged to the console. I'm suspicious that it has to do with the seg fault errors that we've been getting from Jest due to ESM problems, but those were always reproducible locally as well so I'm still investigating. Any ideas are most welcome as well!

**Comment by outSH** [comment]
@petermetz Yeah, I've noticed this some time ago too and it indeed works flawlessly on my machine as well (even though I use roguhly exact same setup as CI!). This test was passing when I've created the list, I think it started failing after https://github.com/hyperledger/cacti/commit/d70488a82e9c1d6958ac3ab0368f3c3bfca378c6#diff-3dc426ffa27f30f292289225a0e941ab0406286a34d200e597748fce0414a90c but I also have no idea what is causing it, ESM problem seem possible

**Comment by petermetz** [comment]
@outSH That link seems like a solid clue, thank you very much! I'll focus my investigation on that file and the code that it tests!

**Comment by petermetz** [comment]
@outSH I've just opened the PR to finish the last one. I can't prove it 100% but I think it's still Jest doing seg faults when we have dynamic imports in the code. My theory is that it only manifests on low core count CPUs with less parallelism and that's why we can't reproduce it at all on local machines.
