### ISSUE TITLE
docs(whitepaper): split whitepaper into multiple files

### ISSUE THREAD

**Issue by petermetz** [hyperledger/cacti#405]
### Description
As a person contributing to the whitepaper I do not want to be blocked by pending PRs on sections of the whitepaper that are not related to another section that I wish to update so that I don't have to be concerned about producing difficult to resolve merge conflicts.

### Acceptance Criteria
1. Whitepaper is broken up into separate .md files at least a new file for each top level section that we have
2. PDF build still works
3. HTML build still works

cc: @takeutak @jonathan-m-hamilton @sfuji822

**Comment by AzaharaC** [comment]
working on this.

**Comment by takeutak** [comment]
@AzaharaC Sorry for my late replying (due to the consecutive national holidays in my country).
In your suggestion, I am worried that the readability of the markdown document will decrease since the whitepaper is separated to multiple files. I'm sure that the readability of the markdown file itself is also important.

> If you want to discuss the need for this pr, we can do it with @petermetz at the next meeting we have.
Thanks. Would you discuss about this topic on the next meeting?
